export const ACTION_AUTOCOMPLETE_SEARCH = 'AUTOCOMPLETE_SEARCH';
export const ACTION_CURRENT_CONDITION = 'CURRENT_CONDITION';
export const ACTION_FORECAST = 'FORECAST';
export const ACTION_UPDATE_CITIES = 'UPDATE_CITIES';
export const ACTION_ADD_FAVORITE = 'ADD_FAVORITE';
export const ACTION_REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const ACTION_CHANGE_TOGGLE = 'CHANGE_TOGGLE';
